on:
  release:
    types: [created]

permissions: write-all

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, android, openbsd, freebsd]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: "386"
            goos: android
          - goarch: amd64
            goos: android
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.20.5.linux-amd64.tar.gz"
          project_path: "./"
          binary_name: "gorecord"
          build_command: make build-action
          extra_files: LICENSE README.md
